export const CATEGORIES = [
    {
        id: "cat-fried-momos",
        title: "Fried Momos",
        slug: "fried-momos",
        image: "/choose1.png",
        description: "Crispy golden fried momos with spicy red dip.",
        itemCount: 4,
        href: "/foods?category=fried-momos",
    },
    {
        id: "cat-steam-momos",
        title: "Steam Momos",
        slug: "steam-momos",
        image: "/choose2.png",
        description: "Authentic hot steamed dumplings filled with fresh veggies & paneer.",
        itemCount: 4,
        href: "/foods?category=steam-momos",
    },
    {
        id: "cat-creamy-momos",
        title: "Creamy Momos",
        slug: "creamy-momos",
        image: "/choose3.png",
        description: "Tossed in rich creamy garlic and seasoned sauce.",
        itemCount: 4,
        href: "/foods?category=creamy-momos",
    },
    {
        id: "cat-gravy-momos",
        title: "Gravy Momos",
        slug: "gravy-momos",
        image: "/choose4.png",
        description: "Succulent momos drenched in sizzling spicy gravy.",
        itemCount: 4,
        href: "/foods?category=gravy-momos",
    },
    {
        id: "cat-kurkure-momos",
        title: "Kurkure Momos",
        slug: "kurkure-momos",
        image: "/choose1.png",
        description: "Super crunchy coating layered with special peri-peri herbs.",
        itemCount: 4,
        href: "/foods?category=kurkure-momos",
    },
    {
        id: "cat-spring-rolls",
        title: "Spring Rolls",
        slug: "spring-rolls",
        image: "/choose2.png",
        description: "Crispy thin wrappers loaded with stir fried veggies.",
        itemCount: 4,
        href: "/foods?category=spring-rolls",
    },
    {
        id: "cat-french-fries",
        title: "French Fries",
        slug: "french-fries",
        image: "/choose3.png",
        description: "Crispy potato fries tossed in peri peri and cheesy dips.",
        itemCount: 3,
        href: "/foods?category=french-fries",
    },
    {
        id: "cat-chaap",
        title: "Chaap Specials",
        slug: "chaap",
        image: "/choose4.png",
        description: "Tender soya chaap grilled in malai and spicy tandoori flavors.",
        itemCount: 4,
        href: "/foods?category=chaap",
    },
    {
        id: "cat-chowmein",
        title: "Chowmein & Noodles",
        slug: "chowmein",
        image: "/choose1.png",
        description: "Wok-tossed noodles with fresh crunchy vegetables & sauces.",
        itemCount: 4,
        href: "/foods?category=chowmein",
    },
    {
        id: "cat-fried-rice",
        title: "Fried Rice",
        slug: "fried-rice",
        image: "/choose2.png",
        description: "Aromatic basmati rice stir-fried with vegetables & paneer.",
        itemCount: 2,
        href: "/foods?category=fried-rice",
    },
    {
        id: "cat-chilli-potato",
        title: "Chilli Potato",
        slug: "chilli-potato",
        image: "/choose3.png",
        description: "Crisp fried potato fingers tossed in spicy chili honey glaze.",
        itemCount: 2,
        href: "/foods?category=chilli-potato",
    },
    {
        id: "cat-pasta",
        title: "Italian Pasta",
        slug: "pasta",
        image: "/choose4.png",
        description: "Creamy white sauce and rich tangy red sauce pastas.",
        itemCount: 2,
        href: "/foods?category=pasta",
    },
    {
        id: "cat-special-items",
        title: "Special Items",
        slug: "special-items",
        image: "/choose1.png",
        description: "Paneer popcorn, cutlets and gooey cheese balls.",
        itemCount: 3,
        href: "/foods?category=special-items",
    },
    {
        id: "cat-samosa",
        title: "Samosa Corner",
        slug: "samosa",
        image: "/choose2.png",
        description: "Crispy stuffed samosas in paneer, malai chaap & pizza styles.",
        itemCount: 4,
        href: "/foods?category=samosa",
    },
    {
        id: "cat-burgers-sandwiches",
        title: "Burgers & Sandwiches",
        slug: "burgers-sandwiches",
        image: "/choose3.png",
        description: "Loaded grilled burgers and toasted cheese sandwiches.",
        itemCount: 7,
        href: "/foods?category=burgers-sandwiches",
    },
    {
        id: "cat-combos",
        title: "Special Combos & Cold Coffee",
        slug: "combos",
        image: "/choose4.png",
        description: "Value meal combos with cold coffee, burgers and snacks.",
        itemCount: 3,
        href: "/foods?category=combos",
    },
];

export const PRODUCTS = [
    {
        id: "fm-1",
        title: "Paneer Fried Momo",
        slug: "paneer-fried-momo",
        category: "fried-momos",
        categoryName: "Fried Momos",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 80.00,
        totalDiscount: "60.00",
        discount: "-15%",
        rating: 5,
        ratingCount: 128,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks", "dinner"],
        description: "Crispy fried momos filled with seasoned fresh paneer and herbs.",
        href: "/foods?category=fried-momos",
    },
    {
        id: "fm-2",
        title: "Veg Fried Momo",
        slug: "veg-fried-momo",
        category: "fried-momos",
        categoryName: "Fried Momos",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 70.00,
        totalDiscount: "55.00",
        discount: "-10%",
        rating: 5,
        ratingCount: 94,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Golden fried momos stuffed with crunchy cabbage, carrots and spices.",
        href: "/foods?category=fried-momos",
    },
    {
        id: "fm-3",
        title: "Soyabin Fried Momo",
        slug: "soyabin-fried-momo",
        category: "fried-momos",
        categoryName: "Fried Momos",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 70.00,
        totalDiscount: "55.00",
        discount: "-10%",
        rating: 5,
        ratingCount: 82,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Protein-packed fried dumplings with juicy spiced soya filling.",
        href: "/foods?category=fried-momos",
    },
    {
        id: "fm-4",
        title: "Wheat Fried Momo",
        slug: "wheat-fried-momo",
        category: "fried-momos",
        categoryName: "Fried Momos",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 70.00,
        totalDiscount: "55.00",
        discount: "-10%",
        rating: 5,
        ratingCount: 75,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Wholesome atta wheat outer crust filled with vegetables and fried crisp.",
        href: "/foods?category=fried-momos",
    },

    {
        id: "sm-1",
        title: "Paneer Steam Momo",
        slug: "paneer-steam-momo",
        category: "steam-momos",
        categoryName: "Steam Momos",
        cuisine: "Fast Food",
        image: "/choose2.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 70.00,
        totalDiscount: "60.00",
        discount: "-15%",
        rating: 5,
        ratingCount: 160,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks", "dinner"],
        description: "Hot steamed dumplings stuffed with cottage cheese and herbs.",
        href: "/foods?category=steam-momos",
    },
    {
        id: "sm-2",
        title: "Veg Steam Momo",
        slug: "veg-steam-momo",
        category: "steam-momos",
        categoryName: "Steam Momos",
        cuisine: "Fast Food",
        image: "/choose2.png",
        price: "40.00",
        rawPrice: 40.00,
        halfPrice: 40.00,
        fullPrice: 60.00,
        totalDiscount: "45.00",
        discount: "-10%",
        rating: 5,
        ratingCount: 140,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Classic tender steamed momos packed with finely chopped garden vegetables.",
        href: "/foods?category=steam-momos",
    },
    {
        id: "sm-3",
        title: "Soyabin Steam Momo",
        slug: "soyabin-steam-momo",
        category: "steam-momos",
        categoryName: "Steam Momos",
        cuisine: "Fast Food",
        image: "/choose2.png",
        price: "40.00",
        rawPrice: 40.00,
        halfPrice: 40.00,
        fullPrice: 60.00,
        totalDiscount: "45.00",
        discount: "-10%",
        rating: 5,
        ratingCount: 88,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Healthy steamed soya chunks dumplings served with red garlic chutney.",
        href: "/foods?category=steam-momos",
    },
    {
        id: "sm-4",
        title: "Wheat Steam Momo",
        slug: "wheat-steam-momo",
        category: "steam-momos",
        categoryName: "Steam Momos",
        cuisine: "Fast Food",
        image: "/choose2.png",
        price: "40.00",
        rawPrice: 40.00,
        halfPrice: 40.00,
        fullPrice: 60.00,
        totalDiscount: "45.00",
        discount: "-10%",
        rating: 5,
        ratingCount: 92,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Guilt-free 100% whole wheat steamed momos filled with fresh veggies.",
        href: "/foods?category=steam-momos",
    },

    {
        id: "cm-1",
        title: "Paneer Creamy Momo",
        slug: "paneer-creamy-momo",
        category: "creamy-momos",
        categoryName: "Creamy Momos",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 110.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 115,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks", "dinner"],
        description: "Paneer momos tossed in velvety rich cream, butter, and oregano seasoning.",
        href: "/foods?category=creamy-momos",
    },
    {
        id: "cm-2",
        title: "Veg Creamy Momo",
        slug: "veg-creamy-momo",
        category: "creamy-momos",
        categoryName: "Creamy Momos",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 100.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 105,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Steamed veg dumplings simmered in rich creamy white garlic dressing.",
        href: "/foods?category=creamy-momos",
    },
    {
        id: "cm-3",
        title: "Soyabin Creamy Momo",
        slug: "soyabin-creamy-momo",
        category: "creamy-momos",
        categoryName: "Creamy Momos",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 100.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 78,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Tender soya momos drenched in a rich garlic cream sauce.",
        href: "/foods?category=creamy-momos",
    },
    {
        id: "cm-4",
        title: "Wheat Creamy Momo",
        slug: "wheat-creamy-momo",
        category: "creamy-momos",
        categoryName: "Creamy Momos",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 100.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 65,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Whole wheat momos tossed in chef's special spiced cream blend.",
        href: "/foods?category=creamy-momos",
    },

    {
        id: "gm-1",
        title: "Paneer Gravy Momo",
        slug: "paneer-gravy-momo",
        category: "gravy-momos",
        categoryName: "Gravy Momos",
        cuisine: "Fast Food",
        image: "/choose4.png",
        price: "80.00",
        rawPrice: 80.00,
        halfPrice: 80.00,
        fullPrice: 120.00,
        totalDiscount: "90.00",
        discount: "-10%",
        rating: 5,
        ratingCount: 132,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["dinner", "lunch"],
        description: "Paneer momos cooked in rich tomato and spicy desi Chinese style gravy.",
        href: "/foods?category=gravy-momos",
    },
    {
        id: "gm-2",
        title: "Veg Gravy Momo",
        slug: "veg-gravy-momo",
        category: "gravy-momos",
        categoryName: "Gravy Momos",
        cuisine: "Fast Food",
        image: "/choose4.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 110.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 110,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["dinner", "lunch"],
        description: "Steamed veg dumplings simmered in fiery, savory schezwan style gravy.",
        href: "/foods?category=gravy-momos",
    },
    {
        id: "gm-3",
        title: "Soyabin Gravy Momo",
        slug: "soyabin-gravy-momo",
        category: "gravy-momos",
        categoryName: "Gravy Momos",
        cuisine: "Fast Food",
        image: "/choose4.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 110.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 74,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["dinner", "lunch"],
        description: "Soyabin momos coated in flavorful hot gravy with spring onions.",
        href: "/foods?category=gravy-momos",
    },
    {
        id: "gm-4",
        title: "Wheat Gravy Momo",
        slug: "wheat-gravy-momo",
        category: "gravy-momos",
        categoryName: "Gravy Momos",
        cuisine: "Fast Food",
        image: "/choose4.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 110.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 68,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["dinner", "lunch"],
        description: "Whole wheat momos simmered in thick spicy tandoori gravy sauce.",
        href: "/foods?category=gravy-momos",
    },

    {
        id: "km-1",
        title: "Paneer Kurkure Momos",
        slug: "paneer-kurkure-momos",
        category: "kurkure-momos",
        categoryName: "Kurkure Momos",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 120.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 190,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks", "dinner"],
        description: "Ultra crunchy crumb coated momos stuffed with spiced paneer.",
        href: "/foods?category=kurkure-momos",
    },
    {
        id: "km-2",
        title: "Veg Kurkure Momos",
        slug: "veg-kurkure-momos",
        category: "kurkure-momos",
        categoryName: "Kurkure Momos",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 100.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 155,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks"],
        description: "Crunchy flakes coated veg momos seasoned with peri-peri masala.",
        href: "/foods?category=kurkure-momos",
    },
    {
        id: "km-3",
        title: "Soyabin Kurkure Momos",
        slug: "soyabin-kurkure-momos",
        category: "kurkure-momos",
        categoryName: "Kurkure Momos",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 100.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 88,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Crisp kurkure shell packed with flavored soya keema.",
        href: "/foods?category=kurkure-momos",
    },
    {
        id: "km-4",
        title: "Wheat Kurkure Momo",
        slug: "wheat-kurkure-momo",
        category: "kurkure-momos",
        categoryName: "Kurkure Momos",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 100.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 72,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Whole wheat momos fried with extra crunchy crust.",
        href: "/foods?category=kurkure-momos",
    },

    {
        id: "sr-1",
        title: "Veg Spring Roll",
        slug: "veg-spring-roll",
        category: "spring-rolls",
        categoryName: "Spring Rolls",
        cuisine: "Chinese",
        image: "/choose2.png",
        price: "30.00",
        rawPrice: 30.00,
        halfPrice: 30.00,
        fullPrice: 50.00,
        totalDiscount: "35.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 140,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Thin crispy rolls filled with stir-fried Chinese cabbage & noodles.",
        href: "/foods?category=spring-rolls",
    },
    {
        id: "sr-2",
        title: "Veg Kurkure Roll",
        slug: "veg-kurkure-roll",
        category: "spring-rolls",
        categoryName: "Spring Rolls",
        cuisine: "Chinese",
        image: "/choose2.png",
        price: "40.00",
        rawPrice: 40.00,
        halfPrice: 40.00,
        fullPrice: 70.00,
        totalDiscount: "45.00",
        discount: "-11%",
        rating: 5,
        ratingCount: 96,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Extra crispy kurkure battered spring roll loaded with veggies.",
        href: "/foods?category=spring-rolls",
    },
    {
        id: "sr-3",
        title: "Paneer Roll",
        slug: "paneer-roll",
        category: "spring-rolls",
        categoryName: "Spring Rolls",
        cuisine: "Chinese",
        image: "/choose2.png",
        price: "40.00",
        rawPrice: 40.00,
        halfPrice: 40.00,
        fullPrice: 70.00,
        totalDiscount: "45.00",
        discount: "-11%",
        rating: 5,
        ratingCount: 112,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks"],
        description: "Crispy golden roll filled with spiced paneer cubes and veggies.",
        href: "/foods?category=spring-rolls",
    },
    {
        id: "sr-4",
        title: "Paneer Kurkure Roll",
        slug: "paneer-kurkure-roll",
        category: "spring-rolls",
        categoryName: "Spring Rolls",
        cuisine: "Chinese",
        image: "/choose2.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 90.00,
        totalDiscount: "60.00",
        discount: "-16%",
        rating: 5,
        ratingCount: 108,
        isPopular: false,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks"],
        description: "Crusted kurkure layer stuffed with soft paneer filling.",
        href: "/foods?category=spring-rolls",
    },

    {
        id: "ff-1",
        title: "Peri Peri Fries",
        slug: "peri-peri-fries",
        category: "french-fries",
        categoryName: "French Fries",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "40.00",
        rawPrice: 40.00,
        halfPrice: 40.00,
        fullPrice: 70.00,
        totalDiscount: "45.00",
        discount: "-11%",
        rating: 5,
        ratingCount: 175,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks"],
        description: "Golden crispy potato fries generously dusted with spicy peri peri mix.",
        href: "/foods?category=french-fries",
    },
    {
        id: "ff-2",
        title: "Creamy Fries",
        slug: "creamy-fries",
        category: "french-fries",
        categoryName: "French Fries",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 100.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 120,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Hot french fries smothered with rich cheese cream dressing.",
        href: "/foods?category=french-fries",
    },
    {
        id: "ff-3",
        title: "Crunchy Fries",
        slug: "crunchy-fries",
        category: "french-fries",
        categoryName: "French Fries",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 100.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 95,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Double fried extra crunchy potato wedges seasoned with herbs.",
        href: "/foods?category=french-fries",
    },

    {
        id: "ch-1",
        title: "Malai Chaap",
        slug: "malai-chaap",
        category: "chaap",
        categoryName: "Chaap Specials",
        cuisine: "North Indian",
        image: "/choose4.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 80.00,
        totalDiscount: "60.00",
        discount: "-15%",
        rating: 5,
        ratingCount: 220,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["dinner", "lunch", "snacks"],
        description: "Succulent soya chaap marinated in fresh cream, cashew paste, and mild spices.",
        href: "/foods?category=chaap",
    },
    {
        id: "ch-2",
        title: "Butter Malai Chaap",
        slug: "butter-malai-chaap",
        category: "chaap",
        categoryName: "Chaap Specials",
        cuisine: "North Indian",
        image: "/choose4.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 90.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 180,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["dinner", "lunch"],
        description: "Tender soya chaap tossed in extra melting Amul butter and rich cream.",
        href: "/foods?category=chaap",
    },
    {
        id: "ch-3",
        title: "Chilli Chaap",
        slug: "chilli-chaap",
        category: "chaap",
        categoryName: "Chaap Specials",
        cuisine: "Chinese",
        image: "/choose4.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 100.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 140,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks", "dinner"],
        description: "Crispy soya chaap tossed with capsicum, onions, and spicy chilli garlic sauce.",
        href: "/foods?category=chaap",
    },
    {
        id: "ch-4",
        title: "Crunchy Chaap",
        slug: "crunchy-chaap",
        category: "chaap",
        categoryName: "Chaap Specials",
        cuisine: "North Indian",
        image: "/choose4.png",
        price: "40.00",
        rawPrice: 40.00,
        halfPrice: 40.00,
        fullPrice: 70.00,
        totalDiscount: "45.00",
        discount: "-11%",
        rating: 5,
        ratingCount: 110,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Crisp kurkure-coated fried soya chaap served with mint chutney.",
        href: "/foods?category=chaap",
    },

    {
        id: "cw-1",
        title: "Veg Chowmein",
        slug: "veg-chowmein",
        category: "chowmein",
        categoryName: "Chowmein & Noodles",
        cuisine: "Chinese",
        image: "/choose1.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 90.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 195,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["lunch", "dinner", "snacks"],
        description: "Classic street-style noodles tossed with cabbage, capsicum, carrots, and soy sauce.",
        href: "/foods?category=chowmein",
    },
    {
        id: "cw-2",
        title: "Paneer Chowmein",
        slug: "paneer-chowmein",
        category: "chowmein",
        categoryName: "Chowmein & Noodles",
        cuisine: "Chinese",
        image: "/choose1.png",
        price: "80.00",
        rawPrice: 80.00,
        halfPrice: 80.00,
        fullPrice: 110.00,
        totalDiscount: "90.00",
        discount: "-11%",
        rating: 5,
        ratingCount: 165,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["lunch", "dinner"],
        description: "Wok-tossed noodles with golden sauteed paneer cubes and crunchy veggies.",
        href: "/foods?category=chowmein",
    },
    {
        id: "cw-3",
        title: "Singapuri Chowmein",
        slug: "singapuri-chowmein",
        category: "chowmein",
        categoryName: "Chowmein & Noodles",
        cuisine: "Chinese",
        image: "/choose1.png",
        price: "80.00",
        rawPrice: 80.00,
        halfPrice: 80.00,
        fullPrice: 110.00,
        totalDiscount: "90.00",
        discount: "-11%",
        rating: 5,
        ratingCount: 125,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["lunch", "dinner"],
        description: "Spicy and tangy noodles with curry powder, paneer, and shredded vegetables.",
        href: "/foods?category=chowmein",
    },
    {
        id: "cw-4",
        title: "Butter Chowmein",
        slug: "butter-chowmein",
        category: "chowmein",
        categoryName: "Chowmein & Noodles",
        cuisine: "Chinese",
        image: "/choose1.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 100.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 130,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["lunch", "dinner"],
        description: "Aromatic noodles tossed in rich Amul butter and savoury seasoning.",
        href: "/foods?category=chowmein",
    },

    {
        id: "fr-1",
        title: "Veg Fried Rice",
        slug: "veg-fried-rice",
        category: "fried-rice",
        categoryName: "Fried Rice",
        cuisine: "Chinese",
        image: "/choose2.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 90.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 145,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["lunch", "dinner"],
        description: "Fluffy basmati rice wok-tossed with chopped veggies, soy sauce, and aromatic peppers.",
        href: "/foods?category=fried-rice",
    },
    {
        id: "fr-2",
        title: "Paneer Fried Rice",
        slug: "paneer-fried-rice",
        category: "fried-rice",
        categoryName: "Fried Rice",
        cuisine: "Chinese",
        image: "/choose2.png",
        price: "80.00",
        rawPrice: 80.00,
        halfPrice: 80.00,
        fullPrice: 100.00,
        totalDiscount: "90.00",
        discount: "-11%",
        rating: 5,
        ratingCount: 155,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["lunch", "dinner"],
        description: "Savory fried rice loaded with fried soft paneer cubes and spring greens.",
        href: "/foods?category=fried-rice",
    },

    {
        id: "cp-1",
        title: "Chilli Potato",
        slug: "chilli-potato",
        category: "chilli-potato",
        categoryName: "Chilli Potato",
        cuisine: "Chinese",
        image: "/choose3.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 100.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 185,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks", "dinner"],
        description: "Crispy fried potato fingers coated in spicy chili garlic sauce with bell peppers.",
        href: "/foods?category=chilli-potato",
    },
    {
        id: "cp-2",
        title: "Honey Chilli Potato",
        slug: "honey-chilli-potato",
        category: "chilli-potato",
        categoryName: "Chilli Potato",
        cuisine: "Chinese",
        image: "/choose3.png",
        price: "80.00",
        rawPrice: 80.00,
        halfPrice: 80.00,
        fullPrice: 120.00,
        totalDiscount: "90.00",
        discount: "-11%",
        rating: 5,
        ratingCount: 210,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks", "dinner"],
        description: "Sweet, spicy, and crispy potatoes glazed in pure honey, chili, and toasted sesame.",
        href: "/foods?category=chilli-potato",
    },

    {
        id: "ps-1",
        title: "White Sauce Pasta",
        slug: "white-sauce-pasta",
        category: "pasta",
        categoryName: "Italian Pasta",
        cuisine: "Italian",
        image: "/choose4.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 120.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 170,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["lunch", "dinner", "snacks"],
        description: "Penne pasta bathed in creamy bechamel cheese sauce with sweet corn and bell peppers.",
        href: "/foods?category=pasta",
    },
    {
        id: "ps-2",
        title: "Red Sauce Pasta",
        slug: "red-sauce-pasta",
        category: "pasta",
        categoryName: "Italian Pasta",
        cuisine: "Italian",
        image: "/choose4.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 120.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 145,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["lunch", "dinner", "snacks"],
        description: "Zesty arrabbiata tomato sauce pasta infused with Italian basil and garlic.",
        href: "/foods?category=pasta",
    },

    {
        id: "sp-1",
        title: "Paneer Popcorn",
        slug: "paneer-popcorn",
        category: "special-items",
        categoryName: "Special Items",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 120.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 160,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks"],
        description: "Bite-sized crunchy battered paneer poppers served with special dip.",
        href: "/foods?category=special-items",
    },
    {
        id: "sp-2",
        title: "Paneer Cutlet",
        slug: "paneer-cutlet",
        category: "special-items",
        categoryName: "Special Items",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 120.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 110,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Crisp spiced patties made of mashed paneer, potato, and aromatic herbs.",
        href: "/foods?category=special-items",
    },
    {
        id: "sp-3",
        title: "Cheese Balls",
        slug: "cheese-balls",
        category: "special-items",
        categoryName: "Special Items",
        cuisine: "Fast Food",
        image: "/choose1.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 120.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 195,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks"],
        description: "Crispy fried golden spheres with molten oozing cheese inside.",
        href: "/foods?category=special-items",
    },

    {
        id: "sam-1",
        title: "Paneer Samosa (1 Pc)",
        slug: "paneer-samosa",
        category: "samosa",
        categoryName: "Samosa Corner",
        cuisine: "Street Food",
        image: "/choose2.png",
        price: "30.00",
        rawPrice: 30.00,
        halfPrice: 30.00,
        fullPrice: 30.00,
        totalDiscount: "35.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 140,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["breakfast", "snacks"],
        description: "Flaky pastry cone packed with seasoned spicy paneer filling.",
        href: "/foods?category=samosa",
    },
    {
        id: "sam-2",
        title: "Malai Chaap Samosa (1 Pc)",
        slug: "malai-chaap-samosa",
        category: "samosa",
        categoryName: "Samosa Corner",
        cuisine: "Street Food",
        image: "/choose2.png",
        price: "30.00",
        rawPrice: 30.00,
        halfPrice: 30.00,
        fullPrice: 30.00,
        totalDiscount: "35.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 125,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["breakfast", "snacks"],
        description: "Unique fusion samosa stuffed with rich creamy malai soya chaap.",
        href: "/foods?category=samosa",
    },
    {
        id: "sam-3",
        title: "Chowmein Samosa (1 Pc / 2 Pc)",
        slug: "chowmein-samosa",
        category: "samosa",
        categoryName: "Samosa Corner",
        cuisine: "Street Food",
        image: "/choose2.png",
        price: "25.00",
        rawPrice: 25.00,
        halfPrice: 25.00,
        fullPrice: 40.00,
        totalDiscount: "30.00",
        discount: "-16%",
        rating: 5,
        ratingCount: 110,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["breakfast", "snacks"],
        description: "Crunchy triangular samosa filled with spicy desi chowmein noodles.",
        href: "/foods?category=samosa",
    },
    {
        id: "sam-4",
        title: "Pizza Samosa (1 Pc)",
        slug: "pizza-samosa",
        category: "samosa",
        categoryName: "Samosa Corner",
        cuisine: "Street Food",
        image: "/choose2.png",
        price: "30.00",
        rawPrice: 30.00,
        halfPrice: 30.00,
        fullPrice: 30.00,
        totalDiscount: "35.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 135,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["breakfast", "snacks"],
        description: "Stuffed with mozzarella cheese, pizza sauce, corn, and Italian herbs.",
        href: "/foods?category=samosa",
    },

    {
        id: "bg-1",
        title: "Veg Burger",
        slug: "veg-burger",
        category: "burgers-sandwiches",
        categoryName: "Burgers & Sandwiches",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "30.00",
        rawPrice: 30.00,
        halfPrice: 30.00,
        fullPrice: 30.00,
        totalDiscount: "35.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 180,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Crispy potato veggie patty layered with lettuce, onions, and burger mayo.",
        href: "/foods?category=burgers-sandwiches",
    },
    {
        id: "bg-2",
        title: "Paneer Burger",
        slug: "paneer-burger",
        category: "burgers-sandwiches",
        categoryName: "Burgers & Sandwiches",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "40.00",
        rawPrice: 40.00,
        halfPrice: 40.00,
        fullPrice: 40.00,
        totalDiscount: "50.00",
        discount: "-20%",
        rating: 5,
        ratingCount: 210,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks"],
        description: "Juicy thick spiced paneer slice with cheese sauce in toasted sesame buns.",
        href: "/foods?category=burgers-sandwiches",
    },
    {
        id: "bg-3",
        title: "Cheese Burger",
        slug: "cheese-burger",
        category: "burgers-sandwiches",
        categoryName: "Burgers & Sandwiches",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 50.00,
        totalDiscount: "60.00",
        discount: "-16%",
        rating: 5,
        ratingCount: 165,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks"],
        description: "Loaded with melted cheddar cheese slice, crispy patty, and fresh veggies.",
        href: "/foods?category=burgers-sandwiches",
    },
    {
        id: "bg-4",
        title: "Crunchy Burger",
        slug: "crunchy-burger",
        category: "burgers-sandwiches",
        categoryName: "Burgers & Sandwiches",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 60.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 130,
        isPopular: false,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks"],
        description: "Special extra crunchy patty topped with chipotle sauce and jalapenos.",
        href: "/foods?category=burgers-sandwiches",
    },
    {
        id: "sw-1",
        title: "Veg Sandwich",
        slug: "veg-sandwich",
        category: "burgers-sandwiches",
        categoryName: "Burgers & Sandwiches",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 50.00,
        totalDiscount: "60.00",
        discount: "-16%",
        rating: 5,
        ratingCount: 120,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["breakfast", "snacks"],
        description: "Grilled jumbo bread filled with cucumbers, tomatoes, bell pepper, and chutney.",
        href: "/foods?category=burgers-sandwiches",
    },
    {
        id: "sw-2",
        title: "Paneer Sandwich",
        slug: "paneer-sandwich",
        category: "burgers-sandwiches",
        categoryName: "Burgers & Sandwiches",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "60.00",
        rawPrice: 60.00,
        halfPrice: 60.00,
        fullPrice: 60.00,
        totalDiscount: "70.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 175,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["breakfast", "snacks"],
        description: "Butter-toasted sandwich stuffed with spiced crumbled paneer and herbs.",
        href: "/foods?category=burgers-sandwiches",
    },
    {
        id: "sw-3",
        title: "Cheese Sandwich",
        slug: "cheese-sandwich",
        category: "burgers-sandwiches",
        categoryName: "Burgers & Sandwiches",
        cuisine: "Fast Food",
        image: "/choose3.png",
        price: "70.00",
        rawPrice: 70.00,
        halfPrice: 70.00,
        fullPrice: 70.00,
        totalDiscount: "80.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 150,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["breakfast", "snacks"],
        description: "Double grilled cheese sandwich loaded with mozzarella and cheese spread.",
        href: "/foods?category=burgers-sandwiches",
    },

    {
        id: "cb-1",
        title: "Cold Coffee",
        slug: "cold-coffee",
        category: "combos",
        categoryName: "Special Combos & Cold Coffee",
        cuisine: "Beverages",
        image: "/choose4.png",
        price: "50.00",
        rawPrice: 50.00,
        halfPrice: 50.00,
        fullPrice: 50.00,
        totalDiscount: "60.00",
        discount: "-16%",
        rating: 5,
        ratingCount: 230,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["snacks"],
        description: "Creamy frothy chilled coffee blended with chocolate syrup and thick milk.",
        href: "/foods?category=combos",
    },
    {
        id: "cb-2",
        title: "₹150 Super Saver Combo",
        slug: "150-super-saver-combo",
        category: "combos",
        categoryName: "Special Combos & Cold Coffee",
        cuisine: "Fast Food",
        image: "/choose4.png",
        price: "150.00",
        rawPrice: 150.00,
        halfPrice: 150.00,
        fullPrice: 150.00,
        totalDiscount: "170.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 310,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["lunch", "dinner", "snacks"],
        description: "Complete meal: 1x Chilled Cold Coffee + 1x Paneer Burger + 1x Paneer Sandwich.",
        href: "/foods?category=combos",
    },
    {
        id: "cb-3",
        title: "₹179 Mega Feast Combo",
        slug: "179-mega-feast-combo",
        category: "combos",
        categoryName: "Special Combos & Cold Coffee",
        cuisine: "Fast Food",
        image: "/choose4.png",
        price: "179.00",
        rawPrice: 179.00,
        halfPrice: 179.00,
        fullPrice: 179.00,
        totalDiscount: "210.00",
        discount: "-15%",
        rating: 5,
        ratingCount: 280,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["lunch", "dinner", "snacks"],
        description: "Bestseller: Veg + Paneer Momos (Half) + French Fries (Half) + Malai Chaap (Half) + Free Cold Drink.",
        href: "/foods?category=combos",
    },
];

export const getPopularProducts = () => {
    return PRODUCTS.filter((item) => item.isPopular);
};

export const getFeaturedProducts = () => {
    return PRODUCTS.filter((item) => item.isFeatured);
};

export const getProductsByCategory = (categorySlug) => {
    if (!categorySlug || categorySlug === "all") return PRODUCTS;
    return PRODUCTS.filter((item) => item.category === categorySlug);
};

export const getProductsByMeal = (mealType) => {
    if (!mealType || mealType === "all") return PRODUCTS;
    return PRODUCTS.filter((item) => item.mealType?.includes(mealType));
};

export const getProductById = (id) => {
    return PRODUCTS.find((item) => item.id === id);
};

export const getProductBySlug = (slug) => {
    return PRODUCTS.find((item) => item.slug === slug);
};
