export const CATEGORIES = [
    {
        id: "cat-1",
        title: "Today's Special",
        slug: "todays-special",
        image: "/choose1.png",
        description: "Chef's exclusive signature dishes prepared with artisanal touch.",
        itemCount: 8,
        href: "/foods?category=todays-special",
    },
    {
        id: "cat-2",
        title: "Pure Vegetarian",
        slug: "veg",
        image: "/choose2.png",
        description: "100% fresh, authentic vegetarian delights and paneer delicacies.",
        itemCount: 18,
        href: "/foods?category=veg",
    },
    {
        id: "cat-3",
        title: "Non-Veg Specials",
        slug: "non-veg",
        image: "/cat-image.png",
        description: "Succulent chicken, tender mutton, and royal slow-cooked curries.",
        itemCount: 22,
        href: "/foods?category=non-veg",
    },
    {
        id: "cat-4",
        title: "Crispy Starters & Tandoor",
        slug: "starters",
        image: "/choose3.png",
        description: "Smoky charcoal kebabs, crispy appetizers, and fiery tikkas.",
        itemCount: 14,
        href: "/foods?category=starters",
    },
    {
        id: "cat-5",
        title: "Morning Breakfast",
        slug: "breakfast",
        image: "/choose4.png",
        description: "Freshly cooked hot breakfasts to fuel your day with goodness.",
        itemCount: 10,
        href: "/foods?category=breakfast",
    },
    {
        id: "cat-6",
        title: "Executive Lunch Meals",
        slug: "lunch",
        image: "/cat-image.png",
        description: "Complete wholesome thalis, combos, and express office meals.",
        itemCount: 12,
        href: "/foods?category=lunch",
    },
    {
        id: "cat-7",
        title: "Evening Snacks & Rolls",
        slug: "snacks",
        image: "/choose1.png",
        description: "Flaky kathi rolls, street snacks, and crunchy tea-time bites.",
        itemCount: 15,
        href: "/foods?category=snacks",
    },
    {
        id: "cat-8",
        title: "Royal Dinner Feast",
        slug: "dinner",
        image: "/choose2.png",
        description: "Hearty handi curries, freshly baked breads, and aromatic rice.",
        itemCount: 16,
        href: "/foods?category=dinner",
    },
    {
        id: "cat-9",
        title: "Authentic South Indian",
        slug: "south-indian",
        image: "/choose4.png",
        description: "Crispy dosas, fluffy idlis, and traditional coastal recipes.",
        itemCount: 9,
        href: "/foods?category=south-indian",
    },
    {
        id: "cat-10",
        title: "Desi Chinese & Wok",
        slug: "chinese",
        image: "/choose3.png",
        description: "Sizzling noodles, spicy fried rice, and fiery manchurian dishes.",
        itemCount: 12,
        href: "/foods?category=chinese",
    },
    {
        id: "cat-11",
        title: "Italian & Woodfire Pizzas",
        slug: "italian",
        image: "/cat-image.png",
        description: "Hand-stretched cheesy pizzas, creamy pastas, and garlic breads.",
        itemCount: 11,
        href: "/foods?category=italian",
    },
    {
        id: "cat-12",
        title: "Desserts & Shakes",
        slug: "desserts",
        image: "/choose1.png",
        description: "Royal gulab jamun, thick milkshakes, and indulgent sweets.",
        itemCount: 10,
        href: "/foods?category=desserts",
    },
];

export const PRODUCTS = [
    {
        id: "prod-1",
        title: "Special Handi Dum Biryani",
        slug: "special-handi-dum-biryani",
        category: "non-veg",
        categoryName: "Non-Veg Specials",
        cuisine: "Mughlai",
        image: "/cat-image.png",
        price: "30.06",
        rawPrice: 30.06,
        totalDiscount: "35.00",
        discount: "-15%",
        rating: 5,
        ratingCount: 142,
        isPopular: true,
        isFeatured: true,
        isVeg: false,
        mealType: ["lunch", "dinner"],
        description: "Royal slow-cooked aromatic basmati rice layered with saffron, herbs, and tender meat.",
        href: "/menu/non-veg/special-handi-dum-biryani",
    },
    {
        id: "prod-2",
        title: "Smoky Tandoori Chicken Tikka",
        slug: "smoky-tandoori-chicken-tikka",
        category: "starters",
        categoryName: "Crispy Starters & Tandoor",
        cuisine: "North Indian",
        image: "/choose1.png",
        price: "28.52",
        rawPrice: 28.52,
        totalDiscount: "32.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 98,
        isPopular: true,
        isFeatured: true,
        isVeg: false,
        mealType: ["snacks", "dinner"],
        description: "Charcoal grilled boneless chunks marinated in spiced yogurt and mustard oil glaze.",
        href: "/menu/starters/smoky-tandoori-chicken-tikka",
    },
    {
        id: "prod-3",
        title: "Paneer Butter Masala Handi",
        slug: "paneer-butter-masala-handi",
        category: "veg",
        categoryName: "Pure Vegetarian",
        cuisine: "North Indian",
        image: "/choose2.png",
        price: "24.18",
        rawPrice: 24.18,
        totalDiscount: "28.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 120,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["lunch", "dinner"],
        description: "Soft cottage cheese cubes simmered in a velvety tomato, cashew, and rich butter gravy.",
        href: "/menu/veg/paneer-butter-masala-handi",
    },
    {
        id: "prod-4",
        title: "Crispy Masala Dosa",
        slug: "crispy-masala-dosa",
        category: "south-indian",
        categoryName: "Authentic South Indian",
        cuisine: "South Indian",
        image: "/choose4.png",
        price: "16.50",
        rawPrice: 16.50,
        totalDiscount: "19.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 88,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["breakfast", "snacks"],
        description: "Golden crispy fermented crepe stuffed with spiced potato masala, served with 3 chutneys and sambar.",
        href: "/menu/south-indian/crispy-masala-dosa",
    },
    {
        id: "prod-5",
        title: "Chilli Garlic Hakka Noodles",
        slug: "chilli-garlic-hakka-noodles",
        category: "chinese",
        categoryName: "Desi Chinese & Wok",
        cuisine: "Chinese",
        image: "/choose3.png",
        price: "19.20",
        rawPrice: 19.20,
        totalDiscount: "22.50",
        discount: "-15%",
        rating: 5,
        ratingCount: 110,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["lunch", "dinner", "snacks"],
        description: "Wok-tossed noodles with crunchy vegetables, burnt garlic, and tangy spicy soy sauces.",
        href: "/menu/chinese/chilli-garlic-hakka-noodles",
    },
    {
        id: "prod-6",
        title: "Woodfire Margherita Pizza",
        slug: "woodfire-margherita-pizza",
        category: "italian",
        categoryName: "Italian & Woodfire Pizzas",
        cuisine: "Italian",
        image: "/cat-image.png",
        price: "26.00",
        rawPrice: 26.00,
        totalDiscount: "30.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 95,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["lunch", "dinner", "snacks"],
        description: "Hand-tossed artisan crust topped with San Marzano tomato sauce, fresh basil, and mozzarella.",
        href: "/menu/italian/woodfire-margherita-pizza",
    },
    {
        id: "prod-7",
        title: "Butter Chicken Supreme",
        slug: "butter-chicken-supreme",
        category: "todays-special",
        categoryName: "Today's Special",
        cuisine: "North Indian",
        image: "/choose1.png",
        price: "32.40",
        rawPrice: 32.40,
        totalDiscount: "36.00",
        discount: "-10%",
        rating: 5,
        ratingCount: 210,
        isPopular: true,
        isFeatured: true,
        isVeg: false,
        mealType: ["dinner", "lunch"],
        description: "Tandoori grilled chicken pulled and simmered in our signature silky makhani gravy.",
        href: "/menu/todays-special/butter-chicken-supreme",
    },
    {
        id: "prod-8",
        title: "Deluxe Amritsari Chole Bhature",
        slug: "deluxe-amritsari-chole-bhature",
        category: "breakfast",
        categoryName: "Morning Breakfast",
        cuisine: "North Indian",
        image: "/choose2.png",
        price: "18.00",
        rawPrice: 18.00,
        totalDiscount: "21.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 130,
        isPopular: true,
        isFeatured: false,
        isVeg: true,
        mealType: ["breakfast", "lunch"],
        description: "Puffed golden bhaturas served with spicy dark Amritsari chole, pickled onions, and green chilli.",
        href: "/menu/breakfast/deluxe-amritsari-chole-bhature",
    },
    {
        id: "prod-9",
        title: "Kathi Double Egg Chicken Roll",
        slug: "kathi-double-egg-chicken-roll",
        category: "snacks",
        categoryName: "Evening Snacks & Rolls",
        cuisine: "Street Food",
        image: "/choose3.png",
        price: "18.50",
        rawPrice: 18.50,
        totalDiscount: "21.00",
        discount: "-12%",
        rating: 5,
        ratingCount: 92,
        isPopular: true,
        isFeatured: false,
        isVeg: false,
        mealType: ["snacks", "dinner"],
        description: "Crispy layered egg paratha wrapped around spicy chicken tikka, pickled onions, and mint chutney.",
        href: "/menu/snacks/kathi-double-egg-chicken-roll",
    },
    {
        id: "prod-10",
        title: "Royal Shahi Gulab Jamun",
        slug: "royal-shahi-gulab-jamun",
        category: "desserts",
        categoryName: "Desserts & Shakes",
        cuisine: "Dessert",
        image: "/choose4.png",
        price: "12.00",
        rawPrice: 12.00,
        totalDiscount: "15.00",
        discount: "-20%",
        rating: 5,
        ratingCount: 118,
        isPopular: true,
        isFeatured: true,
        isVeg: true,
        mealType: ["dinner", "desserts"],
        description: "Warm soft milk dumplings soaked in cardamom rose syrup and garnished with roasted pistachios.",
        href: "/menu/desserts/royal-shahi-gulab-jamun",
    },
    {
        id: "prod-11",
        title: "Ghee Roast Podi Idli",
        slug: "ghee-roast-podi-idli",
        category: "south-indian",
        categoryName: "Authentic South Indian",
        cuisine: "South Indian",
        image: "/cat-image.png",
        price: "14.00",
        rawPrice: 14.00,
        totalDiscount: "16.50",
        discount: "-15%",
        rating: 5,
        ratingCount: 76,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["breakfast", "snacks"],
        description: "Mini bite-sized idlis tossed in fragrant gun powder podi masala and pure desi ghee.",
        href: "/menu/south-indian/ghee-roast-podi-idli",
    },
    {
        id: "prod-12",
        title: "Sizzling Veg Schezwan Fried Rice",
        slug: "sizzling-veg-schezwan-fried-rice",
        category: "chinese",
        categoryName: "Desi Chinese & Wok",
        cuisine: "Chinese",
        image: "/choose1.png",
        price: "20.50",
        rawPrice: 20.50,
        totalDiscount: "24.00",
        discount: "-14%",
        rating: 5,
        ratingCount: 84,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["lunch", "dinner"],
        description: "Aromatic long grain rice wok-tossed with spicy Schezwan peppers and fresh garden veggies.",
        href: "/menu/chinese/sizzling-veg-schezwan-fried-rice",
    },
    {
        id: "prod-13",
        title: "Creamy Alfredo Chicken Pasta",
        slug: "creamy-alfredo-chicken-pasta",
        category: "italian",
        categoryName: "Italian & Woodfire Pizzas",
        cuisine: "Italian",
        image: "/choose2.png",
        price: "27.50",
        rawPrice: 27.50,
        totalDiscount: "31.00",
        discount: "-11%",
        rating: 5,
        ratingCount: 90,
        isPopular: false,
        isFeatured: true,
        isVeg: false,
        mealType: ["lunch", "dinner"],
        description: "Penne pasta enveloped in a rich parmesan cream sauce with herb grilled chicken strips.",
        href: "/menu/italian/creamy-alfredo-chicken-pasta",
    },
    {
        id: "prod-14",
        title: "Mutton Seekh Kebab Platter",
        slug: "mutton-seekh-kebab-platter",
        category: "starters",
        categoryName: "Crispy Starters & Tandoor",
        cuisine: "Mughlai",
        image: "/choose3.png",
        price: "34.50",
        rawPrice: 34.50,
        totalDiscount: "39.00",
        discount: "-10%",
        rating: 5,
        ratingCount: 86,
        isPopular: false,
        isFeatured: true,
        isVeg: false,
        mealType: ["starters", "dinner"],
        description: "Minced lamb blended with herbs, garlic, and fresh mint skewered and grilled over open flame.",
        href: "/menu/starters/mutton-seekh-kebab-platter",
    },
    {
        id: "prod-15",
        title: "Belgian Chocolate Thick Shake",
        slug: "belgian-chocolate-thick-shake",
        category: "desserts",
        categoryName: "Desserts & Shakes",
        cuisine: "Beverage",
        image: "/choose4.png",
        price: "14.50",
        rawPrice: 14.50,
        totalDiscount: "17.00",
        discount: "-15%",
        rating: 5,
        ratingCount: 104,
        isPopular: false,
        isFeatured: false,
        isVeg: true,
        mealType: ["snacks", "desserts"],
        description: "Ultra-thick milkshake blended with premium dark Belgian chocolate and topped with cocoa crunch.",
        href: "/menu/desserts/belgian-chocolate-thick-shake",
    },
];

export const getPopularProducts = () => {
    return PRODUCTS.filter((item) => item.isPopular);
};

export const getFeaturedProducts = () => {
    return PRODUCTS.filter((item) => item.isFeatured);
};

export const getProductsByCategory = (categorySlug) => {
    if (!categorySlug || categorySlug === "all") return PRODUCTS;
    return PRODUCTS.filter((item) => item.category === categorySlug);
};

export const getProductsByMeal = (mealType) => {
    if (!mealType || mealType === "all") return PRODUCTS;
    return PRODUCTS.filter((item) => item.mealType?.includes(mealType));
};

export const getProductById = (id) => {
    return PRODUCTS.find((item) => item.id === id);
};

export const getProductBySlug = (slug) => {
    return PRODUCTS.find((item) => item.slug === slug);
};
